site_name: Xiangao2018 的个人博客
nav:
  - Home: index.md
  - About: about.md
  - 设计模式:
    - 创建型-简单工厂、工厂方法、抽象工厂: 设计模式/创建型/简单工厂、工厂方法、抽象工厂.md
    - 结构型-装饰器设计模式: 设计模式/结构型/装饰器设计模式.md
    - 结构型-适配器模式: 设计模式/结构型/适配器模式.md
    - 行为型-命令模式: 设计模式/行为型/命令模式.md
    - 行为型-策略模式: 设计模式/行为型/策略模式.md
    - 行为型-观察者模式: 设计模式/行为型/观察者模式.md
 
